/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import javax.swing.ImageIcon;
import javax.swing.ScrollPaneConstants;
import Controlador.*;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import vistas_paneles.*;
import tabla.EstiloTablaHeader;
import tabla.EstiloTablaRenderer;
import tabla.MyScrollbarUI;
//import vistas_paneles.*;

/**
 *
 * @author Danilo
 */
public class Menu extends javax.swing.JFrame {

//    public Matriculas mat = new Matriculas();
    int pos = 0;
    public int menu_calificaciones=0;
    public int sub_menu_calificaciones=0;
  public   Menu_requerimiento mr = new Menu_requerimiento(null, true);
  public Menu_grafica mg = new Menu_grafica(null, true);

   
//   public Inscripciones ins= new Inscripciones();
    
//    public Cronogrma_actividades cro = new Cronogrma_actividades();
    

    /**
     * Creates new form Principal
     */
    public Menu() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(this);
       setIconImage(new ImageIcon(getClass().getResource("/IMG/logo_32px.png")).getImage());

// aqui cambiamos colores del scroll bar
        sc_menu.getVerticalScrollBar().setUI(new MyScrollbarUI());
        sc_menu.getHorizontalScrollBar().setUI(new MyScrollbarUI());

        sc_ventanas.getVerticalScrollBar().setUI(new MyScrollbarUI());
        sc_ventanas.getHorizontalScrollBar().setUI(new MyScrollbarUI());
        //quitamos la seleccion del boton
        nofocus();
        pintar(1);

        Panel_Home p_home = new Panel_Home();
        new cambia_panel(panel_master, p_home);

        // CambiaPanel p=new CambiaPanel(panel_master, new vistas_paneles.Panel_Home());
        // new CambiaPanel(panel_master, new vistas_paneles.pnlHome());
//        Panel_Home p_home = new Panel_Home();
//        new cambia_panel(panel_master, p_home);

     panel_master.setLayout(new java.awt.BorderLayout());
            panel_master.add(p_home);
//
//            panel_master.validate();
        cerrar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_menu_calificaciones = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_menu = new javax.swing.JButton();
        panel_menu = new javax.swing.JPanel();
        sc_menu = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_Experimento = new rojerusan.RSButtonMetro();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_home = new rojerusan.RSButtonMetro();
        btn_semilla = new rojerusan.RSButtonMetro();
        jLabel3 = new javax.swing.JLabel();
        btn_Graficas = new rojerusan.RSButtonMetro();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_Datos = new rojerusan.RSButtonMetro();
        sc_ventanas = new javax.swing.JScrollPane();
        panel_master = new javax.swing.JPanel();

        panel_menu_calificaciones.setBackground(new java.awt.Color(255, 0, 51));
        panel_menu_calificaciones.setAlignmentX(4.0F);
        panel_menu_calificaciones.setAlignmentY(4.0F);

        javax.swing.GroupLayout panel_menu_calificacionesLayout = new javax.swing.GroupLayout(panel_menu_calificaciones);
        panel_menu_calificaciones.setLayout(panel_menu_calificacionesLayout);
        panel_menu_calificacionesLayout.setHorizontalGroup(
            panel_menu_calificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );
        panel_menu_calificacionesLayout.setVerticalGroup(
            panel_menu_calificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(21, 96, 136));
        jPanel2.setForeground(new java.awt.Color(21, 96, 136));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MENÚ");

        btn_menu.setBackground(new java.awt.Color(21, 96, 136));
        btn_menu.setForeground(new java.awt.Color(21, 96, 136));
        btn_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Menu_52x52.png"))); // NOI18N
        btn_menu.setBorder(null);
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panel_menu.setBackground(new java.awt.Color(38, 166, 154));

        sc_menu.setBackground(new java.awt.Color(27, 108, 155));
        sc_menu.setBorder(null);
        sc_menu.setForeground(new java.awt.Color(27, 108, 155));
        sc_menu.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        sc_menu.setToolTipText("");
        sc_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setBackground(new java.awt.Color(27, 108, 155));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar Semillas");

        btn_Experimento.setBackground(new java.awt.Color(27, 108, 155));
        btn_Experimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/experimento_52px.png"))); // NOI18N
        btn_Experimento.setText("  Experimentar");
        btn_Experimento.setActionCommand("          ");
        btn_Experimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExperimentoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MENÚ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" Home");

        btn_home.setBackground(new java.awt.Color(27, 108, 155));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/horarios_52px.png"))); // NOI18N
        btn_home.setText("         HOME                   ");
        btn_home.setActionCommand("          ");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        btn_semilla.setBackground(new java.awt.Color(27, 108, 155));
        btn_semilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/semilla_52px.png"))); // NOI18N
        btn_semilla.setText("   SEMILLAS    ");
        btn_semilla.setActionCommand("          ");
        btn_semilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_semillaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Definir Parámetros");

        btn_Graficas.setBackground(new java.awt.Color(27, 108, 155));
        btn_Graficas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Graficas_52px.png"))); // NOI18N
        btn_Graficas.setText("           Graficas");
        btn_Graficas.setActionCommand("          ");
        btn_Graficas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GraficasActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Graficar Experimentos");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Visualizar Datos");

        btn_Datos.setBackground(new java.awt.Color(27, 108, 155));
        btn_Datos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Data_View_52px.png"))); // NOI18N
        btn_Datos.setText("           Datos");
        btn_Datos.setActionCommand("          ");
        btn_Datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_Datos, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_Experimento, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_Graficas, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_semilla, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_semilla, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Datos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Experimento, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Graficas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        sc_menu.setViewportView(jPanel3);

        javax.swing.GroupLayout panel_menuLayout = new javax.swing.GroupLayout(panel_menu);
        panel_menu.setLayout(panel_menuLayout);
        panel_menuLayout.setHorizontalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sc_menu, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
        );
        panel_menuLayout.setVerticalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sc_menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );

        panel_master.setBackground(new java.awt.Color(255, 255, 255));
        panel_master.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        javax.swing.GroupLayout panel_masterLayout = new javax.swing.GroupLayout(panel_master);
        panel_master.setLayout(panel_masterLayout);
        panel_masterLayout.setHorizontalGroup(
            panel_masterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1134, Short.MAX_VALUE)
        );
        panel_masterLayout.setVerticalGroup(
            panel_masterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        sc_ventanas.setViewportView(panel_master);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sc_ventanas, javax.swing.GroupLayout.PREFERRED_SIZE, 1128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sc_ventanas, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ExperimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExperimentoActionPerformed
        // TODO add your handling code here:
        pintar(3);
Panel_Home p_home = new Panel_Home();
        new cambia_panel(panel_master, p_home);
        
        
           Point punto = MouseInfo.getPointerInfo().getLocation();
        int x1 = punto.x;
        int y1 = punto.y;

        
        //mr.setLocation(x1, y1);
        mr.setVisible(true);
           
      // bs.Entidad="estudiante";
//        Panel_Home p_home = new Panel_Home();
//        new cambia_panel(panel_master, p_home);
    }//GEN-LAST:event_btn_ExperimentoActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed

//        int posicion = panel_menu.getX();
//        if (posicion > -1) {
//            Animacion.Animacion.mover_izquierda(0, -264, 2, 2, panel_menu);
//        } else {
//            Animacion.Animacion.mover_derecha(-264, 0, 2, 2, panel_menu);
//
//            //           x,x,velocidad entre mas es menos
//        }
//        int pos = panel_menu_calificaciones.getX();
//        if (pos > -1) {
//            Animacion.Animacion.mover_derecha(-264, 0, 2, 2, panel_menu_calificaciones);
//        } else {
//
//            Animacion.Animacion.mover_izquierda(0, -264, 2, 2, panel_menu_calificaciones);
//
//            //           x,x,velocidad entre mas es menos
//        }

    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
        pintar(1);

        Panel_Home p_home = new Panel_Home();
        new cambia_panel(panel_master, p_home);
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_semillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_semillaActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
        pintar(2);

        Semilla se = new Semilla();
        new cambia_panel(panel_master, se);
    }//GEN-LAST:event_btn_semillaActionPerformed

    private void btn_GraficasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GraficasActionPerformed
        // TODO add your handling code here:
//         Semilla se = new Semilla();
//         new cambia_panel(panel_master, se);

     pintar(4);
 
 mg.setVisible(true);
    }//GEN-LAST:event_btn_GraficasActionPerformed

    private void btn_DatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DatosActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
          // TODO add your handling code here:
        pintar(5);

        DatosExperimentos de = new DatosExperimentos();
        new cambia_panel(panel_master, de);
        
    }//GEN-LAST:event_btn_DatosActionPerformed

    public void pintar(int pos_mouse) {
        int pos = pos_mouse;
        Color c_precionado = new java.awt.Color(21, 96, 136);
        Color c_sinprecionar = new java.awt.Color(27, 108, 155);

        if (pos == 1) {
            btn_home.setBackground(c_precionado);              //1
                btn_semilla.setBackground(c_sinprecionar);   //2
            btn_Experimento.setBackground(c_sinprecionar);      //3
            btn_Graficas.setBackground(c_sinprecionar);  
            btn_Datos.setBackground(c_sinprecionar);
//4
//            btn_docente.setBackground(c_sinprecionar);         //5
//
//            btn_estudents.setBackground(c_sinprecionar);       //6
//            btn_horarios.setBackground(c_sinprecionar);        //7
//            btn_peri_aca.setBackground(c_sinprecionar);        //8
//            btn_cursos.setBackground(c_sinprecionar);         //9
//
//            btn_congresos.setBackground(c_sinprecionar);      //10
//            btn_diplomados.setBackground(c_sinprecionar);     //11
//            btn_licencias.setBackground(c_sinprecionar);     //12
//            btn_seminarios.setBackground(c_sinprecionar);    //13

//            btn_oec.setBackground(c_sinprecionar);          //14
//            btn_inscriptions.setBackground(c_sinprecionar);  //15
//            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 2) {
            btn_home.setBackground(c_sinprecionar);              //1
            btn_semilla.setBackground(c_precionado);   //2
            btn_Experimento.setBackground(c_sinprecionar);      //3
            btn_Graficas.setBackground(c_sinprecionar);       //4
             btn_Datos.setBackground(c_sinprecionar);
//            btn_docente.setBackground(c_sinprecionar);         //5
//
//            btn_estudents.setBackground(c_sinprecionar);       //6
//            btn_horarios.setBackground(c_sinprecionar);        //7
//            btn_peri_aca.setBackground(c_sinprecionar);        //8
//            btn_cursos.setBackground(c_sinprecionar);         //9

//            btn_congresos.setBackground(c_sinprecionar);      //10
//            btn_diplomados.setBackground(c_sinprecionar);     //11
//            btn_licencias.setBackground(c_sinprecionar);     //12
//            btn_seminarios.setBackground(c_sinprecionar);    //13

//            btn_oec.setBackground(c_sinprecionar);          //14
//            btn_inscriptions.setBackground(c_sinprecionar);  //15
//            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 3) {
            btn_home.setBackground(c_sinprecionar);              //1
            btn_semilla.setBackground(c_sinprecionar);   //2
            btn_Experimento.setBackground(c_precionado);      //3
            btn_Graficas.setBackground(c_sinprecionar);       //4
            btn_Datos.setBackground(c_sinprecionar);      //5
//
//            btn_estudents.setBackground(c_sinprecionar);       //6
//            btn_horarios.setBackground(c_sinprecionar);        //7
//            btn_peri_aca.setBackground(c_sinprecionar);        //8
//            btn_cursos.setBackground(c_sinprecionar);         //9
//
//            btn_congresos.setBackground(c_sinprecionar);      //10
//            btn_diplomados.setBackground(c_sinprecionar);     //11
//            btn_licencias.setBackground(c_sinprecionar);     //12
//            btn_seminarios.setBackground(c_sinprecionar);    //13

//            btn_oec.setBackground(c_sinprecionar);          //14
//            btn_inscriptions.setBackground(c_sinprecionar);  //15
//            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 4) {
            btn_home.setBackground(c_sinprecionar);              //1
            btn_semilla.setBackground(c_sinprecionar);   //2
           btn_Experimento.setBackground(c_sinprecionar);      //3
           btn_Graficas.setBackground(c_precionado);       //4
            btn_Datos.setBackground(c_sinprecionar);    //5
//
//            btn_estudents.setBackground(c_sinprecionar);       //6
//            btn_horarios.setBackground(c_sinprecionar);        //7
//            btn_peri_aca.setBackground(c_sinprecionar);        //8
//            btn_cursos.setBackground(c_sinprecionar);         //9
//
//            btn_congresos.setBackground(c_sinprecionar);      //10
//            btn_diplomados.setBackground(c_sinprecionar);     //11
//            btn_licencias.setBackground(c_sinprecionar);     //12
//            btn_seminarios.setBackground(c_sinprecionar);    //13

//            btn_oec.setBackground(c_sinprecionar);          //14
//            btn_inscriptions.setBackground(c_sinprecionar);  //15
//            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 5) {
           btn_home.setBackground(c_sinprecionar);              //1
           btn_semilla.setBackground(c_sinprecionar);   //2
           btn_Experimento.setBackground(c_sinprecionar);      //3
           btn_Graficas.setBackground(c_sinprecionar);       //4
            btn_Datos.setBackground(c_precionado);    //5
//
//            btn_estudents.setBackground(c_sinprecionar);       //6
//            btn_horarios.setBackground(c_sinprecionar);        //7
//            btn_peri_aca.setBackground(c_sinprecionar);        //8
//            btn_cursos.setBackground(c_sinprecionar);         //9
//
//            btn_congresos.setBackground(c_sinprecionar);      //10
//            btn_diplomados.setBackground(c_sinprecionar);     //11
//            btn_licencias.setBackground(c_sinprecionar);     //12
//            btn_seminarios.setBackground(c_sinprecionar);    //13

//            btn_oec.setBackground(c_sinprecionar);          //14
//            btn_inscriptions.setBackground(c_sinprecionar);  //15
//            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 6) {
            btn_Experimento.setBackground(c_sinprecionar);              //1
            btn_semilla.setBackground(c_sinprecionar);   //2
//            btn_crono_cali.setBackground(c_sinprecionar);      //3
//            btn_crono_act.setBackground(c_sinprecionar);       //4
//            btn_docente.setBackground(c_sinprecionar);         //5
//
//            btn_estudents.setBackground(c_precionado);       //6
//            btn_horarios.setBackground(c_sinprecionar);        //7
//            btn_peri_aca.setBackground(c_sinprecionar);        //8
//            btn_cursos.setBackground(c_sinprecionar);         //9
//
//            btn_congresos.setBackground(c_sinprecionar);      //10
//            btn_diplomados.setBackground(c_sinprecionar);     //11
//            btn_licencias.setBackground(c_sinprecionar);     //12
//            btn_seminarios.setBackground(c_sinprecionar);    //13

//            btn_oec.setBackground(c_sinprecionar);          //14
//            btn_inscriptions.setBackground(c_sinprecionar);  //15
//            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 7) {
            btn_Experimento.setBackground(c_sinprecionar);              //1
            btn_semilla.setBackground(c_sinprecionar);   //2
//            btn_crono_cali.setBackground(c_sinprecionar);      //3
//            btn_crono_act.setBackground(c_sinprecionar);       //4
//            btn_docente.setBackground(c_sinprecionar);         //5
//
//            btn_estudents.setBackground(c_sinprecionar);       //6
//            btn_horarios.setBackground(c_precionado);        //7
//            btn_peri_aca.setBackground(c_sinprecionar);        //8
//            btn_cursos.setBackground(c_sinprecionar);         //9
//
//            btn_congresos.setBackground(c_sinprecionar);      //10
//            btn_diplomados.setBackground(c_sinprecionar);     //11
//            btn_licencias.setBackground(c_sinprecionar);     //12
//            btn_seminarios.setBackground(c_sinprecionar);    //13

//            btn_oec.setBackground(c_sinprecionar);          //14
//            btn_inscriptions.setBackground(c_sinprecionar);  //15
//            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 8) {
            btn_Experimento.setBackground(c_sinprecionar);              //1
            btn_semilla.setBackground(c_sinprecionar);   //2
//            btn_crono_cali.setBackground(c_sinprecionar);      //3
//            btn_crono_act.setBackground(c_sinprecionar);       //4
//            btn_docente.setBackground(c_sinprecionar);         //5
//
//            btn_estudents.setBackground(c_sinprecionar);       //6
//            btn_horarios.setBackground(c_sinprecionar);        //7
//            btn_peri_aca.setBackground(c_precionado);        //8
//            btn_cursos.setBackground(c_sinprecionar);         //9

//            btn_congresos.setBackground(c_sinprecionar);      //10
//            btn_diplomados.setBackground(c_sinprecionar);     //11
//            btn_licencias.setBackground(c_sinprecionar);     //12
//            btn_seminarios.setBackground(c_sinprecionar);    //13

//            btn_oec.setBackground(c_sinprecionar);          //14
//            btn_inscriptions.setBackground(c_sinprecionar);  //15
//            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 9) {
            btn_Experimento.setBackground(c_sinprecionar);              //1
            btn_semilla.setBackground(c_sinprecionar);   //2
//            btn_crono_cali.setBackground(c_sinprecionar);      //3
//            btn_crono_act.setBackground(c_sinprecionar);       //4
//            btn_docente.setBackground(c_sinprecionar);         //5
//
//            btn_estudents.setBackground(c_sinprecionar);       //6
//            btn_horarios.setBackground(c_sinprecionar);        //7
//            btn_peri_aca.setBackground(c_sinprecionar);        //8
//            btn_cursos.setBackground(c_precionado);         //9
//
//            btn_congresos.setBackground(c_sinprecionar);      //10
//            btn_diplomados.setBackground(c_sinprecionar);     //11
//            btn_licencias.setBackground(c_sinprecionar);     //12
//            btn_seminarios.setBackground(c_sinprecionar);    //13

//            btn_oec.setBackground(c_sinprecionar);          //14
//            btn_inscriptions.setBackground(c_sinprecionar);  //15
//            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 10) {
            btn_Experimento.setBackground(c_sinprecionar);              //1
            btn_semilla.setBackground(c_sinprecionar);   //2
//            btn_crono_cali.setBackground(c_sinprecionar);      //3
//            btn_crono_act.setBackground(c_sinprecionar);       //4
//            btn_docente.setBackground(c_sinprecionar);         //5
//
//            btn_estudents.setBackground(c_sinprecionar);       //6
//            btn_horarios.setBackground(c_sinprecionar);        //7
//            btn_peri_aca.setBackground(c_sinprecionar);        //8
//            btn_cursos.setBackground(c_sinprecionar);         //9
//
//            btn_congresos.setBackground(c_precionado);      //10
//            btn_diplomados.setBackground(c_sinprecionar);     //11
//            btn_licencias.setBackground(c_sinprecionar);     //12
//            btn_seminarios.setBackground(c_sinprecionar);    //13

//            btn_oec.setBackground(c_sinprecionar);          //14
//            btn_inscriptions.setBackground(c_sinprecionar);  //15
//            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 11) {
            btn_Experimento.setBackground(c_sinprecionar);              //1
            btn_semilla.setBackground(c_sinprecionar);   //2
//            btn_crono_cali.setBackground(c_sinprecionar);      //3
//            btn_crono_act.setBackground(c_sinprecionar);       //4
//            btn_docente.setBackground(c_sinprecionar);         //5
//
//            btn_estudents.setBackground(c_sinprecionar);       //6
//            btn_horarios.setBackground(c_sinprecionar);        //7
//            btn_peri_aca.setBackground(c_sinprecionar);        //8
//            btn_cursos.setBackground(c_sinprecionar);         //9
//
//            btn_congresos.setBackground(c_sinprecionar);      //10
//            btn_diplomados.setBackground(c_precionado);     //11
//            btn_licencias.setBackground(c_sinprecionar);     //12
//            btn_seminarios.setBackground(c_sinprecionar);    //13

//            btn_oec.setBackground(c_sinprecionar);          //14
//            btn_inscriptions.setBackground(c_sinprecionar);  //15
//            btn_matriculas.setBackground(c_sinprecionar);    //16

        }

        if (pos == 12) {
            btn_Experimento.setBackground(c_sinprecionar);              //1
            btn_semilla.setBackground(c_sinprecionar);   //2
//            btn_crono_cali.setBackground(c_sinprecionar);      //3
//            btn_crono_act.setBackground(c_sinprecionar);       //4
//            btn_docente.setBackground(c_sinprecionar);         //5
//
//            btn_estudents.setBackground(c_sinprecionar);       //6
//            btn_horarios.setBackground(c_sinprecionar);        //7
//            btn_peri_aca.setBackground(c_sinprecionar);        //8
//            btn_cursos.setBackground(c_sinprecionar);         //9
//
//            btn_congresos.setBackground(c_sinprecionar);      //10
//            btn_diplomados.setBackground(c_sinprecionar);     //11
//            btn_licencias.setBackground(c_precionado);     //12
//            btn_seminarios.setBackground(c_sinprecionar);    //13

//            btn_oec.setBackground(c_sinprecionar);          //14
//            btn_inscriptions.setBackground(c_sinprecionar);  //15
//            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 13) {
            btn_Experimento.setBackground(c_sinprecionar);              //1
            btn_semilla.setBackground(c_sinprecionar);   //2
//            btn_crono_cali.setBackground(c_sinprecionar);      //3
//            btn_crono_act.setBackground(c_sinprecionar);       //4
//            btn_docente.setBackground(c_sinprecionar);         //5
////
//            btn_estudents.setBackground(c_sinprecionar);       //6
//            btn_horarios.setBackground(c_sinprecionar);        //7
//            btn_peri_aca.setBackground(c_sinprecionar);        //8
//            btn_cursos.setBackground(c_sinprecionar);         //9
//
//            btn_congresos.setBackground(c_sinprecionar);      //10
//            btn_diplomados.setBackground(c_sinprecionar);     //11
//            btn_licencias.setBackground(c_sinprecionar);     //12
//            btn_seminarios.setBackground(c_precionado);    //13

//            btn_oec.setBackground(c_sinprecionar);          //14
//            btn_inscriptions.setBackground(c_sinprecionar);  //15
//            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 14) {
            btn_Experimento.setBackground(c_sinprecionar);              //1
            btn_semilla.setBackground(c_sinprecionar);   //2
//            btn_crono_cali.setBackground(c_sinprecionar);      //3
//            btn_crono_act.setBackground(c_sinprecionar);       //4
//            btn_docente.setBackground(c_sinprecionar);         //5
//
//            btn_estudents.setBackground(c_sinprecionar);       //6
//            btn_horarios.setBackground(c_sinprecionar);        //7
//            btn_peri_aca.setBackground(c_sinprecionar);        //8
//            btn_cursos.setBackground(c_sinprecionar);         //9
//
//            btn_congresos.setBackground(c_sinprecionar);      //10
//            btn_diplomados.setBackground(c_sinprecionar);     //11
//            btn_licencias.setBackground(c_sinprecionar);     //12
//            btn_seminarios.setBackground(c_sinprecionar);    //13

//            btn_oec.setBackground(c_precionado);          //14
//            btn_inscriptions.setBackground(c_sinprecionar);  //15
//            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 15) {
            btn_Experimento.setBackground(c_sinprecionar);              //1
            btn_semilla.setBackground(c_sinprecionar);   //2
//            btn_crono_cali.setBackground(c_sinprecionar);      //3
//            btn_crono_act.setBackground(c_sinprecionar);       //4
//            btn_docente.setBackground(c_sinprecionar);         //5
//
//            btn_estudents.setBackground(c_sinprecionar);       //6
//            btn_horarios.setBackground(c_sinprecionar);        //7
//            btn_peri_aca.setBackground(c_sinprecionar);        //8
//            btn_cursos.setBackground(c_sinprecionar);         //9
//
//            btn_congresos.setBackground(c_sinprecionar);      //10
//            btn_diplomados.setBackground(c_sinprecionar);     //11
//            btn_licencias.setBackground(c_sinprecionar);     //12
//            btn_seminarios.setBackground(c_sinprecionar);    //13

//            btn_oec.setBackground(c_sinprecionar);          //14
//            btn_inscriptions.setBackground(c_precionado);  //15
//            btn_matriculas.setBackground(c_sinprecionar);    //16

        }
        if (pos == 16) {
            btn_Experimento.setBackground(c_sinprecionar);              //1
            btn_semilla.setBackground(c_sinprecionar);   //2
////            btn_crono_cali.setBackground(c_sinprecionar);      //3
//            btn_crono_act.setBackground(c_sinprecionar);       //4
//            btn_docente.setBackground(c_sinprecionar);         //5
//
//            btn_estudents.setBackground(c_sinprecionar);       //6
//            btn_horarios.setBackground(c_sinprecionar);        //7
//            btn_peri_aca.setBackground(c_sinprecionar);        //8
//            btn_cursos.setBackground(c_sinprecionar);         //9
//
//            btn_congresos.setBackground(c_sinprecionar);      //10
//            btn_diplomados.setBackground(c_sinprecionar);     //11
//            btn_licencias.setBackground(c_sinprecionar);     //12
//            btn_seminarios.setBackground(c_sinprecionar);    //13

//            btn_oec.setBackground(c_sinprecionar);          //14
//            btn_inscriptions.setBackground(c_sinprecionar);  //15
//            btn_matriculas.setBackground(c_precionado);    //16

        }

    }

    private void nofocus() {
        btn_menu.setFocusPainted(false);
        btn_Experimento.setFocusPainted(false);;              //1
        btn_semilla.setFocusPainted(false); 
        btn_Datos.setFocusPainted(false);
         btn_home.setFocusPainted(false);
         btn_Graficas.setFocusPainted(false);
        //2
//        btn_crono_cali.setFocusPainted(false);      //3
//        btn_crono_act.setFocusPainted(false);       //4
//        btn_docente.setFocusPainted(false);      //5
//
//        btn_estudents.setFocusPainted(false);       //6
//        btn_horarios.setFocusPainted(false);       //7
//        btn_peri_aca.setFocusPainted(false);        //8
//        btn_cursos.setFocusPainted(false);       //9
//
//        btn_congresos.setFocusPainted(false);      //10
//        btn_diplomados.setFocusPainted(false);     //11
//        btn_licencias.setFocusPainted(false);     //12
//        btn_seminarios.setFocusPainted(false);    //13

//        btn_oec.setFocusPainted(false);         //14
//        btn_inscriptions.setFocusPainted(false);  //15
//        btn_matriculas.setFocusPainted(false);   //16
    }

//////////// validar la salida
    public void cerrar() {
        try {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            //this.setResizable (false);
            addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent e) {
                    int res = confirmar("Alerta", "Esta Seguro que desea salir de la aplicación", "/IMG/Error_100px.png");

                    if (res == 1) {
                        System.exit(0);

                    }

                }
            });
            this.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public int confirmar(String titulo, String texto, String dir_img) {

        int estatus = 9;
        Alertas wa = new Alertas(null, true);
        wa.txt_titu.setText(titulo);
        wa.txt_txt.setText(texto);

        wa.txt_img.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir_img)));

        wa.setVisible(true);

        estatus = wa.respuesta;

        return estatus;
    }
    public void openwindows_calificaciones(int valor){
     if(valor==1){
         
     }   
    }
    
    
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonMetro btn_Datos;
    private rojerusan.RSButtonMetro btn_Experimento;
    private rojerusan.RSButtonMetro btn_Graficas;
    private rojerusan.RSButtonMetro btn_home;
    private javax.swing.JButton btn_menu;
    private rojerusan.RSButtonMetro btn_semilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel panel_master;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JPanel panel_menu_calificaciones;
    private javax.swing.JScrollPane sc_menu;
    private javax.swing.JScrollPane sc_ventanas;
    // End of variables declaration//GEN-END:variables
}
