/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas_paneles;

import Controlador.ControlTrueFalse;
import Controlador.Main;
import Controlador.cambia_panel;
import Modelo.Datos;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tabla.MyScrollbarUI;

import java.awt.MouseInfo;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Danilo
 */
public class Esperimento extends javax.swing.JPanel {
DefaultTableModel md;
    String data[][] = {};
    String cabeza[] = {"Tiempo", "Peso"};// para la cabezera
    
    
    
    
    /**
     * Creates new form Panel_Home
     */
    public Esperimento() {
        initComponents();
        // jLabel6.setBorder(no);

        docente_menu.getVerticalScrollBar().setUI(new MyScrollbarUI());
        docente_menu.getHorizontalScrollBar().setUI(new MyScrollbarUI());

//        consutarTabla_Estudiantes();
//        control_botones();
        nofocus();
//        vaciar_cajas();
Txt_Peso.setText("100.12");
   md = new DefaultTableModel(data, cabeza);//preparamos el modelo de la tabla
        Tabla_dis.setModel(md);   // enviamos el modelo a la tabla


    }

    ////conex
   Datos d= new Datos();
      String direccionBD = d.getDireccionBD();
      String usuarioBD = d.getUsuarioBD();
      String contraBD = d.getContraBD();
    // Instanciamos la clase conectar 
    Modelo.conectar cone1 = new Modelo.conectar();
    // realizamos la conexion
    public Connection cn = cone1.conexion(direccionBD, usuarioBD, contraBD);
    // la conexion se hereda en cn
  ControlTrueFalse Control = new ControlTrueFalse();
  
  int repeticiones;
    int d_experimento;
    int i_tiempo;
    int num_Cuadros;
    ArrayList<Float> tiempo = new ArrayList();
    ArrayList<Float> peso = new ArrayList();
    
    ArrayList<Float> Perdida_Masa_G = new ArrayList();
    ArrayList<Float> Perdida_Masa_P = new ArrayList();
    ArrayList<Float> humedad = new ArrayList();
     ArrayList<Float> Vel_Per_masa = new ArrayList();
     
    public String codigo_semilla="";
    public String Nombre_semilla="";
    public String Num_exp="";
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_nExperimento = new javax.swing.JLabel();
        Btn_AgregarDatos = new rojerusan.RSButtonMetro();
        Btn_Calcular_T = new rojerusan.RSButtonMetro();
        Btn_Graficar = new rojerusan.RSButtonMetro();
        docente_menu = new javax.swing.JScrollPane();
        Tabla_dis = new rojerusan.RSTableMetro();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Txt_Peso = new rojerusan.RSMetroTextPlaceHolder();
        jLabel4 = new javax.swing.JLabel();
        Btn_Siguiente = new rojerusan.RSButtonMetro();
        Txt_Dura_Exp = new rojerusan.RSMetroTextPlaceHolder();
        Txt_Inter_Tiem = new rojerusan.RSMetroTextPlaceHolder();
        Btn_Nuvo_Exp = new rojerusan.RSButtonMetro();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(21, 96, 136));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/experimento_52px.png"))); // NOI18N
        jLabel1.setText("  Experimento N°:");

        txt_nExperimento.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_nExperimento.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nExperimento, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_nExperimento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Btn_AgregarDatos.setBackground(new java.awt.Color(21, 96, 136));
        Btn_AgregarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/add_dat_50px.png"))); // NOI18N
        Btn_AgregarDatos.setText("Agregar Datos");
        Btn_AgregarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AgregarDatosActionPerformed(evt);
            }
        });

        Btn_Calcular_T.setBackground(new java.awt.Color(21, 96, 136));
        Btn_Calcular_T.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Calcular_tabla50px.png"))); // NOI18N
        Btn_Calcular_T.setText("Calcular Tabla");
        Btn_Calcular_T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Calcular_TActionPerformed(evt);
            }
        });

        Btn_Graficar.setBackground(new java.awt.Color(21, 96, 136));
        Btn_Graficar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Graficas_52px.png"))); // NOI18N
        Btn_Graficar.setText("Graficar");
        Btn_Graficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GraficarActionPerformed(evt);
            }
        });

        docente_menu.setBackground(new java.awt.Color(21, 96, 136));

        Tabla_dis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla_dis.setColorBackgoundHead(new java.awt.Color(21, 96, 136));
        Tabla_dis.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        Tabla_dis.setColorBordeHead(new java.awt.Color(21, 96, 136));
        Tabla_dis.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        Tabla_dis.setColorFilasForeground1(new java.awt.Color(21, 96, 136));
        Tabla_dis.setColorFilasForeground2(new java.awt.Color(21, 96, 136));
        Tabla_dis.setColorSelBackgound(new java.awt.Color(27, 108, 155));
        Tabla_dis.setGridColor(new java.awt.Color(255, 255, 255));
        docente_menu.setViewportView(Tabla_dis);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(21, 96, 136));
        jLabel2.setText("Minutos");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(21, 96, 136));
        jLabel3.setText("Minutos");

        Txt_Peso.setForeground(new java.awt.Color(27, 108, 155));
        Txt_Peso.setBorderColor(new java.awt.Color(21, 96, 136));
        Txt_Peso.setBotonColor(new java.awt.Color(21, 96, 136));
        Txt_Peso.setCaretColor(new java.awt.Color(21, 96, 136));
        Txt_Peso.setDisabledTextColor(new java.awt.Color(102, 102, 255));
        Txt_Peso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Peso.setPhColor(new java.awt.Color(27, 108, 155));
        Txt_Peso.setPlaceholder("Masa / Peso  Inicial");
        Txt_Peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_PesoActionPerformed(evt);
            }
        });
        Txt_Peso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_PesoKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(21, 96, 136));
        jLabel4.setText("Gramos");

        Btn_Siguiente.setBackground(new java.awt.Color(21, 96, 136));
        Btn_Siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/guardar_52px.png"))); // NOI18N
        Btn_Siguiente.setText("Guardar Experimento");
        Btn_Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SiguienteActionPerformed(evt);
            }
        });

        Txt_Dura_Exp.setForeground(new java.awt.Color(27, 108, 155));
        Txt_Dura_Exp.setBorderColor(new java.awt.Color(21, 96, 136));
        Txt_Dura_Exp.setBotonColor(new java.awt.Color(21, 96, 136));
        Txt_Dura_Exp.setCaretColor(new java.awt.Color(21, 96, 136));
        Txt_Dura_Exp.setDisabledTextColor(new java.awt.Color(102, 102, 255));
        Txt_Dura_Exp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Dura_Exp.setPhColor(new java.awt.Color(27, 108, 155));
        Txt_Dura_Exp.setPlaceholder("Duración del experimento:");
        Txt_Dura_Exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_Dura_ExpActionPerformed(evt);
            }
        });
        Txt_Dura_Exp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_Dura_ExpKeyTyped(evt);
            }
        });

        Txt_Inter_Tiem.setForeground(new java.awt.Color(27, 108, 155));
        Txt_Inter_Tiem.setBorderColor(new java.awt.Color(21, 96, 136));
        Txt_Inter_Tiem.setBotonColor(new java.awt.Color(21, 96, 136));
        Txt_Inter_Tiem.setCaretColor(new java.awt.Color(21, 96, 136));
        Txt_Inter_Tiem.setDisabledTextColor(new java.awt.Color(102, 102, 255));
        Txt_Inter_Tiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Inter_Tiem.setPhColor(new java.awt.Color(27, 108, 155));
        Txt_Inter_Tiem.setPlaceholder("Intervalo de Tiempo:");
        Txt_Inter_Tiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_Inter_TiemActionPerformed(evt);
            }
        });
        Txt_Inter_Tiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_Inter_TiemKeyTyped(evt);
            }
        });

        Btn_Nuvo_Exp.setBackground(new java.awt.Color(21, 96, 136));
        Btn_Nuvo_Exp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/next_50px.png"))); // NOI18N
        Btn_Nuvo_Exp.setText("Siguiente ");
        Btn_Nuvo_Exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Nuvo_ExpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Txt_Peso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(Txt_Inter_Tiem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(Btn_Calcular_T, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Txt_Dura_Exp, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Btn_AgregarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Btn_Graficar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Btn_Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Btn_Nuvo_Exp, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(docente_menu, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_AgregarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Graficar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Nuvo_Exp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(docente_menu, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_Dura_Exp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txt_Inter_Tiem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(Txt_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)
                        .addComponent(Btn_Calcular_T, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Calcular_TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Calcular_TActionPerformed
       // TODO add your handling code here:
//        Control.ButtonFalse(Btn_Calcular_T);
//        Control.ButtonTrue(Btn_AgregarDatos);
//        Control.ButtonFalse(Btn_Graficar);
//        Control.ButtonFalse(Btn_Siguiente);

        //repeticiones = Integer.parseInt(Txt_N_Experi.getText());
        d_experimento = Integer.parseInt(Txt_Dura_Exp.getText().toString());
        i_tiempo = Integer.parseInt(Txt_Inter_Tiem.getText().toString());
        num_Cuadros = d_experimento / i_tiempo;
        
        
        //////////////////////////////borrar
      
        
        
       
        
        ////////////////////////////borrar
      
        int pos = 0;
        for (int i = 0; i <= d_experimento; i = i + i_tiempo) {
     //String datos[] = {Integer.toString(i)};
            String datos[] = {Float.toString(i)};
            md.addRow(datos);

            pos++;
        }
        

// Control.TxtFalse(Txt_Dura_Exp);
// Control.TxtFalse(Txt_Inter_Tiem);
 Control.TxtFalse(Txt_Peso);
 
 
        
        
        
    }//GEN-LAST:event_Btn_Calcular_TActionPerformed

    private void Btn_AgregarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AgregarDatosActionPerformed
//          Control.ButtonFalse(Btn_Calcular_T);
//        Control.ButtonFalse(Btn_AgregarDatos);
//        Control.ButtonTrue(Btn_Graficar);
//        Control.ButtonFalse(Btn_Siguiente);

        Tabla_dis.setValueAt("100.12", 0, 1);
        for (int i = 1; i <= num_Cuadros; i++) {

            Tabla_dis.setValueAt(JOptionPane.showInputDialog("Ingrese el peso para el minuto: " + Tabla_dis.getValueAt(i, 0).toString()), i, 1);

        }

    }//GEN-LAST:event_Btn_AgregarDatosActionPerformed

    private void Btn_GraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GraficarActionPerformed
     
       Grafica gr=new Grafica(null, true);

        try {

            for (int i = 0; i <= num_Cuadros; i++) {
                tiempo.add(Float.parseFloat(Tabla_dis.getValueAt(i, 0).toString()));
                peso.add(Float.parseFloat(Tabla_dis.getValueAt(i, 1).toString()));
            }
  
            //gra(fm1, "MASA", "TIEMPO VS PESO  ", 1, tiempo, peso, num_Cuadros);
            Controlador.Grafica g = new Controlador.Grafica("MASA", "TIEMPO VS PESO  ", 1);
            g.addgraficaDesdeLista(tiempo, peso, num_Cuadros);
            g.IniciarGraficaIndividual(gr.p_grafica);
            JOptionPane.showMessageDialog(null,Nombre_semilla);
                gr.txt_nom_semilla.setText(Nombre_semilla);
              gr.txt_num_expe.setText(txt_nExperimento.getText().toString());
              gr.txt_nom_semilla1.setText("Experimento Número=");
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e + "  No se pudo graficar");
        }
        try {
            float v1=0;
        float v2=100;
        
         Perdida_Masa_G.add(v1);
         Perdida_Masa_P.add(v2);
         
         for(int i=1; i<= num_Cuadros;i++){
                
             float per_masa_g=peso.get(0)-peso.get(i);
            Perdida_Masa_G.add(per_masa_g);
            
           float per_masa_p=(peso.get(i)*100)/peso.get(0);
           Perdida_Masa_P.add(per_masa_p);  
         }
         
         for(int i=0; i<= num_Cuadros;i++){
           float paso1=(peso.get(0)-peso.get(num_Cuadros-i));
           //JOptionPane.showMessageDialog(null, paso1);
           float paso2=paso1/peso.get(0);
           //JOptionPane.showMessageDialog(null, paso2);
           float paso3=paso2*100;
           
           humedad.add(paso3);   
         }
         Vel_Per_masa .add(v1);
         for(int i=1; i<= num_Cuadros;i++){
           float valor1=(peso.get(i)-peso.get(i-1)); 
           float valor2=(tiempo.get(i)-tiempo.get(i-1));
           float valor3=((valor1/valor2)*-1);
          // JOptionPane.showMessageDialog(null, valor3);
           Vel_Per_masa.add(valor3);
         }
         
         
         
         
         
         
         
         System.out.println("////////////////perdida_mas_g");
       for(int i=0; i<= num_Cuadros;i++){
          System.out.println(Perdida_Masa_G.get(i));
           }
         System.out.println("////////////////perdida_mas_p");
       for(int i=0; i<= num_Cuadros;i++){
          System.out.println(Perdida_Masa_P.get(i));
           }
       
         System.out.println("////////////////humedad");
       for(int i=0; i<= num_Cuadros;i++){
          System.out.println(humedad.get(i));
           }
       
       System.out.println("////////////////velocidad perdida masa");
       for(int i=0; i<= num_Cuadros;i++){
          System.out.println(Vel_Per_masa.get(i));
           }
            
        } catch (Exception e) {
               JOptionPane.showConfirmDialog(null," error al construir las tablas"+e);
        }
        

       
       
//        Control.ButtonFalse(Btn_Calcular_T);
//        Control.ButtonFalse(Btn_AgregarDatos);
//        Control.ButtonFalse(Btn_Graficar);
//        Control.ButtonTrue(Btn_Siguiente);
       
       
       
       
       
       
       
       
       
       
       
       
       
       
      
         gr.setVisible(true);
    }//GEN-LAST:event_Btn_GraficarActionPerformed

    private void Txt_PesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_PesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_PesoActionPerformed

    private void Txt_PesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_PesoKeyTyped
        // TODO add your handling code here:
        char letra=evt.getKeyChar();
        if(!Character.isLetter(letra) && !Character.isSpaceChar(letra)){// si no es letra
            evt.consume();// cancelo ingreso de la letra
        }
    }//GEN-LAST:event_Txt_PesoKeyTyped

    private void Btn_SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SiguienteActionPerformed
        // TODO add your handling code here:
        String num_exp_general="";
          
        num_exp_general = codigo_semilla + "." + txt_nExperimento.getText().toString();
        
     // JOptionPane.showMessageDialog(null, num_exp_general);
        try {
            PreparedStatement pst;
            pst = cn.prepareStatement("INSERT INTO `num_experimentos`(`cod_num_exp`, `duracion_exp`, `intervalo_tiempo_exp`, `peso_inicial_exp`, `cod_exp_sec`) VALUES  (?,?,?,?,?)");

            pst.setString(1, num_exp_general);
            pst.setString(2, Txt_Dura_Exp.getText().toString());
            pst.setString(3, Txt_Inter_Tiem.getText().toString());
            pst.setString(4, Txt_Peso.getText().toString());
            pst.setString(5, codigo_semilla);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "DATOS GUARDADOS EXITOSAMENTE");
        } catch (SQLException ex) {
            
        }
       
        
        
        
        
        
         for (int i = 0; i <= num_Cuadros; i++) { 
            try {
                PreparedStatement pst;
                pst = cn.prepareStatement("INSERT INTO `medicion`( `valor_tiempo`, `valor_peso`, `perdida_masa_g`, `perdida_masa_p`, `humedad`, `velo_per_peso`, `cod_num_exp`) VALUES (?,?,?,?,?,?,?)");
                pst.setString(1, Tabla_dis.getValueAt(i, 0).toString());
                pst.setString(2, Tabla_dis.getValueAt(i, 1).toString());
                pst.setFloat(3, Perdida_Masa_G.get(i));
                pst.setFloat(4, Perdida_Masa_P.get(i));
                pst.setFloat(5, humedad.get(i));
                pst.setFloat(6, Vel_Per_masa.get(i));
                pst.setString(7, num_exp_general);
                pst.executeUpdate();
     //           JOptionPane.showMessageDialog(null, "se guardo el datos " + Tabla_dis.getValueAt(i, 0).toString() + " y " + Tabla_dis.getValueAt(i, 1).toString());
            } catch (SQLException ex) {

  
            }
        }
         
         try {
                PreparedStatement pst = cn.prepareStatement("UPDATE `repeticion` SET `contador`=? WHERE `cod_exp_sec`='"+codigo_semilla+"'");
                pst.setInt(1,Integer.parseInt( txt_nExperimento.getText().toString()));
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "CONTADOR GUARDADOS CON EXITO");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "ERROR AL GUARDAR LOS DATOS" + e.getMessage());
            }

        
        
        
        
        
        
    }//GEN-LAST:event_Btn_SiguienteActionPerformed

    private void Txt_Dura_ExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_Dura_ExpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Dura_ExpActionPerformed

    private void Txt_Dura_ExpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_Dura_ExpKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Dura_ExpKeyTyped

    private void Txt_Inter_TiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_Inter_TiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Inter_TiemActionPerformed

    private void Txt_Inter_TiemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_Inter_TiemKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Inter_TiemKeyTyped

    private void Btn_Nuvo_ExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Nuvo_ExpActionPerformed
        // TODO add your handling code here:
       Main.m.  pintar(3);
Panel_Home p_home = new Panel_Home();
        new cambia_panel(Main.m.panel_master, p_home);
        
        
           Point punto = MouseInfo.getPointerInfo().getLocation();
        int x1 = punto.x;
        int y1 = punto.y;

        
        //mr.setLocation(x1, y1);
        Main.m.mr.setVisible(true);
    }//GEN-LAST:event_Btn_Nuvo_ExpActionPerformed

    public void consutarTabla_Estudiantes() {

        String consultaBD = "SELECT * FROM `experimento_secado` ";
        javax.swing.JTable Tabla = this.Tabla_dis;
        // Enviamos los parametros para la consulta de la tabla
        //  conexion    consulta de la base de datos y el nombre de la tabla
        String cabesera[] = {"Código", "Nombre de la Semilla", "Numero Experimentos", "Fecha"};
        cone1.GetTabla_Sincabeseras_sql_bd(cn, consultaBD, Tabla, cabesera);

    }

    public void consutaBD(String Campo, String txtSQL) {

        //String consultaBD = "SELECT * FROM `docente` WHERE " + Campo + "='" + txtSQL + "'";
          String consultaBD = "SELECT * FROM `estudiante` WHERE " + Campo + " LIKE '" + txtSQL + "_%'";
          //JOptionPane.showMessageDialog(null, consultaBD);
        javax.swing.JTable Tabla = this.Tabla_dis;
        // Enviamos los parametros para la consulta de la tabla
        //  conexion    consulta de la base de datos y el nombre de la tabla
        String cabesera[] = {"Código", "Nombres", "Apellidos", "Dirección", "Teléfono", "Fecha de Naciemiento", "Nacionalidad","Tipo de Sangre"
        };
        cone1.GetTabla_Sincabeseras_sql_bd(cn, consultaBD, Tabla, cabesera);

    }
     public void consutaBD_sinfiltros(String Campo, String txtSQL) {

        String consultaBD = "SELECT * FROM `estudiante` WHERE " + Campo + "='" + txtSQL + "'";
         // String consultaBD = "SELECT * FROM `docente` WHERE " + Campo + " LIKE '" + txtSQL + "_%'";
          //JOptionPane.showMessageDialog(null, consultaBD);
        javax.swing.JTable Tabla = this.Tabla_dis;
        // Enviamos los parametros para la consulta de la tabla
        //  conexion    consulta de la base de datos y el nombre de la tabla
        String cabesera[] = {"Código", "Nombres", "Apellidos", "Dirección", "Teléfono", "Fecha de Naciemiento", "Nacionalidad","Tipo de Sangre"
        };
        cone1.GetTabla_Sincabeseras_sql_bd(cn, consultaBD, Tabla, cabesera);

    }

    public void control_botones() {
        Btn_Calcular_T.setEnabled(false);
        Btn_AgregarDatos.setEnabled(true);
        Btn_Graficar.setEnabled(false);
     
    }

    public void alerta(String titulo, String texto, String dir_img) {

        Alertas wa = new Alertas(null, true);
        wa.txt_titu.setText(titulo);
        wa.txt_txt.setText(texto);

        wa.txt_img.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir_img)));

        wa.setVisible(true);
    }

    public int confirmar(String titulo, String texto, String dir_img) {

        int estatus = 9;
        Alertas wa = new Alertas(null, true);
        wa.txt_titu.setText(titulo);
        wa.txt_txt.setText(texto);

        wa.txt_img.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir_img)));

        wa.setVisible(true);

        estatus = wa.respuesta;

        return estatus;
    }

    private void nofocus() {
        Btn_AgregarDatos.setFocusPainted(false);
        Btn_Graficar.setFocusPainted(false);
        
        Btn_Calcular_T.setFocusPainted(false);

    }

    private void vaciar_cajas() {
        Txt_Peso.setText("");
       
        
      
       
        

        Txt_Peso.setEnabled(false);
      
        Txt_Dura_Exp.setEnabled(false);
         
        
        Tabla_dis.setEnabled(false);
       
          
         
    }

    private void btn_True_false() {
        Btn_Calcular_T.setEnabled(false);
        Btn_AgregarDatos.setEnabled(true);
        Btn_Graficar.setEnabled(false);
        
        Tabla_dis.setEnabled(false);
      
    }
    private void nuevo(){
        Btn_Calcular_T.setEnabled(true);
        Btn_AgregarDatos.setEnabled(false);
        Btn_Graficar.setEnabled(true);
       
        Txt_Peso.setEnabled(true);
       
        Txt_Dura_Exp.setEnabled(true);
        
        
        Tabla_dis.setEnabled(true);

        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonMetro Btn_AgregarDatos;
    private rojerusan.RSButtonMetro Btn_Calcular_T;
    private rojerusan.RSButtonMetro Btn_Graficar;
    private rojerusan.RSButtonMetro Btn_Nuvo_Exp;
    private rojerusan.RSButtonMetro Btn_Siguiente;
    private rojerusan.RSTableMetro Tabla_dis;
    private rojerusan.RSMetroTextPlaceHolder Txt_Dura_Exp;
    private rojerusan.RSMetroTextPlaceHolder Txt_Inter_Tiem;
    private rojerusan.RSMetroTextPlaceHolder Txt_Peso;
    private javax.swing.JScrollPane docente_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel txt_nExperimento;
    // End of variables declaration//GEN-END:variables
}
