/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas_paneles;

import Controlador.Fichero;
import Controlador.Main;
import Controlador.cambia_panel;
import Modelo.Datos;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import tabla.MyScrollbarUI;
import static vistas_paneles.Menu_grafica.RET_OK;

/**
 *
 * @author Danilo
 */
public class Menu_TipoGrafica extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;
    public int respuesta = 3;
    String txt_exp_registrados="";
    String txt_ex_regitro="";
    String txt_cod_sem="";
    
    
    Datos d = new Datos();
    String direccionBD = d.getDireccionBD();
    String usuarioBD = d.getUsuarioBD();
    String contraBD = d.getContraBD();
    // Instanciamos la clase conectar 
    Modelo.conectar cone1 = new Modelo.conectar();
    // realizamos la conexion
    public Connection cn = cone1.conexion(direccionBD, usuarioBD, contraBD);

    /**
     * Creates new form Alertas
     */
    public Menu_TipoGrafica(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(this);
btn_graficar.setEnabled(true);


txt_nombre_semilla.setText("");

        
txt_mensaje_exp.setText("");





        //   this. setIconImage(new ImageIcon(getClass().getResource("/Img_menu/SEPRYTSAV_45x45PX.png")).getImage());
//jScrollPane1.getVerticalScrollBar().setUI(new MyScrollbarUI());
//        jScrollPane1.getHorizontalScrollBar().setUI(new MyScrollbarUI());
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        btn_graficar = new rojerusan.RSButtonMetro();
        txt_titu = new javax.swing.JLabel();
        txt_nombre_semilla = new javax.swing.JLabel();
        txt_mensaje_exp = new javax.swing.JLabel();
        txt_ex_regitro1 = new javax.swing.JLabel();
        btn_graficar1 = new rojerusan.RSButtonMetro();
        btn_graficar2 = new rojerusan.RSButtonMetro();
        btn_graficar3 = new rojerusan.RSButtonMetro();
        btn_graficar4 = new rojerusan.RSButtonMetro();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(21, 96, 136));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        btn_graficar.setBackground(new java.awt.Color(21, 96, 136));
        btn_graficar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Graficas_52px.png"))); // NOI18N
        btn_graficar.setText(" Masa vs Tiempo                          ");
        btn_graficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_graficarActionPerformed(evt);
            }
        });

        txt_titu.setBackground(new java.awt.Color(21, 96, 136));
        txt_titu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_titu.setForeground(new java.awt.Color(21, 96, 136));

        txt_nombre_semilla.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_nombre_semilla.setForeground(new java.awt.Color(21, 96, 136));

        txt_mensaje_exp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_mensaje_exp.setForeground(new java.awt.Color(255, 51, 51));

        txt_ex_regitro1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_ex_regitro1.setForeground(new java.awt.Color(255, 51, 51));
        txt_ex_regitro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/opc_grafica52px_2.png"))); // NOI18N

        btn_graficar1.setBackground(new java.awt.Color(21, 96, 136));
        btn_graficar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Graficas_52px.png"))); // NOI18N
        btn_graficar1.setText(" Pedida Masa(g) vs Tiempo         ");
        btn_graficar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_graficar1ActionPerformed(evt);
            }
        });

        btn_graficar2.setBackground(new java.awt.Color(21, 96, 136));
        btn_graficar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Graficas_52px.png"))); // NOI18N
        btn_graficar2.setText(" Pedida Masa(%) vs Tiempo      ");
        btn_graficar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_graficar2ActionPerformed(evt);
            }
        });

        btn_graficar3.setBackground(new java.awt.Color(21, 96, 136));
        btn_graficar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Graficas_52px.png"))); // NOI18N
        btn_graficar3.setText(" Humedad vs Tiempo                 ");
        btn_graficar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_graficar3ActionPerformed(evt);
            }
        });

        btn_graficar4.setBackground(new java.awt.Color(21, 96, 136));
        btn_graficar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Graficas_52px.png"))); // NOI18N
        btn_graficar4.setText("Vel.Per.Masa (g/min) vs Tiempo");
        btn_graficar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_graficar4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                                .addComponent(btn_graficar4, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_mensaje_exp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(btn_graficar3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_nombre_semilla, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_graficar, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_graficar1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_titu)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btn_graficar2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(txt_ex_regitro1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(txt_ex_regitro1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_graficar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_titu)
                    .addComponent(btn_graficar1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_graficar2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(txt_nombre_semilla, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_graficar3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(txt_mensaje_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_graficar4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 305, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 409, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void btn_graficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_graficarActionPerformed
        int registros=Integer.parseInt(txt_exp_registrados);
int num_exp=Integer.parseInt(txt_ex_regitro);
   if(registros==num_exp){
        ArrayList<Integer> tiempo1 = new ArrayList();
        ArrayList<Integer> peso1 = new ArrayList();
        ArrayList<Integer> tiempo2 = new ArrayList();
        ArrayList<Integer> peso2 = new ArrayList();
        ArrayList<Integer> tiempo3 = new ArrayList();
        ArrayList<Integer> peso3 = new ArrayList();
        ArrayList<Integer> tiempo4 = new ArrayList();
        ArrayList<Integer> peso4 = new ArrayList();
        ArrayList<Integer> tiempo5 = new ArrayList();
        ArrayList<Integer> peso5 = new ArrayList();
        ArrayList<Integer> tiempo6 = new ArrayList();
        ArrayList<Integer> peso6 = new ArrayList();
        ArrayList<Integer> tiempo7 = new ArrayList();
        ArrayList<Integer> peso7 = new ArrayList();
        ArrayList<Integer> tiempo8 = new ArrayList();
        ArrayList<Integer> peso8 = new ArrayList();
        ArrayList<Integer> tiempo9 = new ArrayList();
        ArrayList<Integer> peso9 = new ArrayList();
        ArrayList<Integer> tiempo10 = new ArrayList();
        ArrayList<Integer> peso10 = new ArrayList();
        
        String Codigo_Semilla = "";
        Codigo_Semilla = txt_cod_sem;
        int next = Integer.parseInt(txt_ex_regitro);
        Statement estado;
         Grafica gr=new Grafica(null, true);
        for (int i = 1; i <= next; i++) {

            try {
                String SQL = "SELECT * FROM `medicion` WHERE `cod_num_exp`= '" + Codigo_Semilla + "." + i + "'";
                estado = cn.createStatement();
                ResultSet resultado = estado.executeQuery(SQL);
                //JOptionPane.showMessageDialog(null, SQL);
                while (resultado.next()) {
                   
                    int cod = resultado.getInt(1);
                    //  JOptionPane.showMessageDialog(null, cod);
                    int v_tiempo = resultado.getInt(2);
                    int v_peso = resultado.getInt(3);

                    String cod_num_exp = resultado.getString(8);

                    if (i == 1) {
                        tiempo1.add(v_tiempo);
                        peso1.add(v_peso);
                    }
                    if (i == 2) {
                        tiempo2.add(v_tiempo);
                        peso2.add(v_peso);
                    }
                    if (i == 3) {
                        tiempo3.add(v_tiempo);
                        peso3.add(v_peso);
                    }
                    if (i == 4) {
                        tiempo4.add(v_tiempo);
                        peso4.add(v_peso);
                    }
                    if (i == 5) {
                        tiempo5.add(v_tiempo);
                        peso5.add(v_peso);
                    }
                    if (i == 6) {
                        tiempo6.add(v_tiempo);
                        peso6.add(v_peso);
                    }
                    if (i == 7) {
                        tiempo7.add(v_tiempo);
                        peso7.add(v_peso);
                    }
                     if(i==8){
                        tiempo8.add(v_tiempo);
                    peso8.add(v_peso);
                    }
                    if(i==9){
                        tiempo9.add(v_tiempo);
                    peso9.add(v_peso);
                    }
                      if(i==10){
                        tiempo10.add(v_tiempo);
                    peso10.add(v_peso);
                    }
                     
                }

            } catch (SQLException ex) {
             

            }

        }

        
             Controlador.Grafica gra1=new Controlador.Grafica("MASA", "Masa vs TIEMPO",next );
              gr.txt_nom_semilla.setText(txt_nombre_semilla.getText().toString());
              gr.txt_num_expe.setText(txt_ex_regitro);
        if (next ==1) {
          //  JOptionPane.showMessageDialog(null," entro");
           
            
        gra1.addgrafica(tiempo1, peso1);
       
         gra1.IniciarGraficaGeneral(gr.p_grafica);
        
        }// fin if
        if (next ==2) {
          //  JOptionPane.showMessageDialog(null," entro");
            
           gra1.addgrafica2(tiempo1, peso1,tiempo2, peso2);
       
           gra1.IniciarGraficaGeneral(gr.p_grafica);
        
        }// fin if
        if (next ==3) {
          //  JOptionPane.showMessageDialog(null," entro");
           
            
            
           gra1.addgrafica3(tiempo1, peso1, tiempo2, peso2, tiempo3, peso3);
      
         gra1.IniciarGraficaGeneral(gr.p_grafica);
        
        }// fin if
        
        if (next ==4) {
          //  JOptionPane.showMessageDialog(null," entro");
           
          
            gra1.addgrafica4(tiempo1, peso1, tiempo2, peso2, tiempo3, peso3, tiempo4, peso4);
      
         gra1.IniciarGraficaGeneral(gr.p_grafica);
        
        }// fin if
        
        if (next ==5) {
          //  JOptionPane.showMessageDialog(null," entro");
           
            
          
            gra1.addgrafica5(tiempo1, peso1, tiempo2, peso2, tiempo3, peso3, tiempo4, peso4, tiempo5, peso5);
      
         gra1.IniciarGraficaGeneral(gr.p_grafica);
        
        }//
        
        
        
        
        
         gr.setVisible(true);
        doClose(RET_OK);
   }// fin if
   else{
     alerta("Alerta", "Aun faltan Experimentos que Registrar", "/Img_alertas/Error_100px.png");   
 txt_mensaje_exp.setText("¡ Aun Faltan experiementos que registrar para esta semilla!");
   }
        
    }//GEN-LAST:event_btn_graficarActionPerformed

    private void btn_graficar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_graficar1ActionPerformed
        int registros=Integer.parseInt(txt_exp_registrados);
int num_exp=Integer.parseInt(txt_ex_regitro);
   if(registros==num_exp){
        ArrayList<Integer> tiempo1 = new ArrayList();
        ArrayList<Integer> peso1 = new ArrayList();
        ArrayList<Integer> tiempo2 = new ArrayList();
        ArrayList<Integer> peso2 = new ArrayList();
        ArrayList<Integer> tiempo3 = new ArrayList();
        ArrayList<Integer> peso3 = new ArrayList();
        ArrayList<Integer> tiempo4 = new ArrayList();
        ArrayList<Integer> peso4 = new ArrayList();
        ArrayList<Integer> tiempo5 = new ArrayList();
        ArrayList<Integer> peso5 = new ArrayList();
        ArrayList<Integer> tiempo6 = new ArrayList();
        ArrayList<Integer> peso6 = new ArrayList();
        ArrayList<Integer> tiempo7 = new ArrayList();
        ArrayList<Integer> peso7 = new ArrayList();
        ArrayList<Integer> tiempo8 = new ArrayList();
        ArrayList<Integer> peso8 = new ArrayList();
        ArrayList<Integer> tiempo9 = new ArrayList();
        ArrayList<Integer> peso9 = new ArrayList();
        ArrayList<Integer> tiempo10 = new ArrayList();
        ArrayList<Integer> peso10 = new ArrayList();
        
        String Codigo_Semilla = "";
        Codigo_Semilla = txt_cod_sem;
        int next = Integer.parseInt(txt_ex_regitro);
        Statement estado;
         Grafica gr=new Grafica(null, true);
        for (int i = 1; i <= next; i++) {

            try {
                String SQL = "SELECT * FROM `medicion` WHERE `cod_num_exp`= '" + Codigo_Semilla + "." + i + "'";
                estado = cn.createStatement();
                ResultSet resultado = estado.executeQuery(SQL);
                //JOptionPane.showMessageDialog(null, SQL);
                while (resultado.next()) {
                   
                    int cod = resultado.getInt(1);
                    //  JOptionPane.showMessageDialog(null, cod);
                    int v_tiempo = resultado.getInt(2);
                    int v_peso = resultado.getInt(4);

                    String cod_num_exp = resultado.getString(8);

                    if (i == 1) {
                        tiempo1.add(v_tiempo);
                        peso1.add(v_peso);
                    }
                    if (i == 2) {
                        tiempo2.add(v_tiempo);
                        peso2.add(v_peso);
                    }
                    if (i == 3) {
                        tiempo3.add(v_tiempo);
                        peso3.add(v_peso);
                    }
                    if (i == 4) {
                        tiempo4.add(v_tiempo);
                        peso4.add(v_peso);
                    }
                    if (i == 5) {
                        tiempo5.add(v_tiempo);
                        peso5.add(v_peso);
                    }
                    if (i == 6) {
                        tiempo6.add(v_tiempo);
                        peso6.add(v_peso);
                    }
                    if (i == 7) {
                        tiempo7.add(v_tiempo);
                        peso7.add(v_peso);
                    }
                     if(i==8){
                        tiempo8.add(v_tiempo);
                    peso8.add(v_peso);
                    }
                    if(i==9){
                        tiempo9.add(v_tiempo);
                    peso9.add(v_peso);
                    }
                      if(i==10){
                        tiempo10.add(v_tiempo);
                    peso10.add(v_peso);
                    }
                     
                }

            } catch (SQLException ex) {
             

            }

        }

        
             Controlador.Grafica gra1=new Controlador.Grafica("PERDIDA DE MASA(g)", "PERDIDA DE MASA(g) vs TIEMPO",next );
              gr.txt_nom_semilla.setText(txt_nombre_semilla.getText().toString());
              gr.txt_num_expe.setText(txt_ex_regitro);
        if (next ==1) {
          //  JOptionPane.showMessageDialog(null," entro");
           
            
        gra1.addgrafica(tiempo1, peso1);
       
         gra1.IniciarGraficaGeneral(gr.p_grafica);
        
        }// fin if
        if (next ==2) {
          //  JOptionPane.showMessageDialog(null," entro");
            
           gra1.addgrafica2(tiempo1, peso1,tiempo2, peso2);
       
           gra1.IniciarGraficaGeneral(gr.p_grafica);
        
        }// fin if
        if (next ==3) {
          //  JOptionPane.showMessageDialog(null," entro");
           
            
            
           gra1.addgrafica3(tiempo1, peso1, tiempo2, peso2, tiempo3, peso3);
      
         gra1.IniciarGraficaGeneral(gr.p_grafica);
        
        }// fin if
        
        if (next ==4) {
          //  JOptionPane.showMessageDialog(null," entro");
           
          
            gra1.addgrafica4(tiempo1, peso1, tiempo2, peso2, tiempo3, peso3, tiempo4, peso4);
      
         gra1.IniciarGraficaGeneral(gr.p_grafica);
        
        }// fin if
        
        if (next ==5) {
          //  JOptionPane.showMessageDialog(null," entro");
           
            
          
            gra1.addgrafica5(tiempo1, peso1, tiempo2, peso2, tiempo3, peso3, tiempo4, peso4, tiempo5, peso5);
      
         gra1.IniciarGraficaGeneral(gr.p_grafica);
        
        }//
        
        
        
        
        
         gr.setVisible(true);
        doClose(RET_OK);
   }// fin if
   else{
     alerta("Alerta", "Aun faltan Experimentos que Registrar", "/Img_alertas/Error_100px.png");   
 txt_mensaje_exp.setText("¡ Aun Faltan experiementos que registrar para esta semilla!");
   }
        
    }//GEN-LAST:event_btn_graficar1ActionPerformed

    private void btn_graficar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_graficar2ActionPerformed
        // TODO add your handling code here:
         int registros=Integer.parseInt(txt_exp_registrados);
int num_exp=Integer.parseInt(txt_ex_regitro);
   if(registros==num_exp){
        ArrayList<Integer> tiempo1 = new ArrayList();
        ArrayList<Integer> peso1 = new ArrayList();
        ArrayList<Integer> tiempo2 = new ArrayList();
        ArrayList<Integer> peso2 = new ArrayList();
        ArrayList<Integer> tiempo3 = new ArrayList();
        ArrayList<Integer> peso3 = new ArrayList();
        ArrayList<Integer> tiempo4 = new ArrayList();
        ArrayList<Integer> peso4 = new ArrayList();
        ArrayList<Integer> tiempo5 = new ArrayList();
        ArrayList<Integer> peso5 = new ArrayList();
        ArrayList<Integer> tiempo6 = new ArrayList();
        ArrayList<Integer> peso6 = new ArrayList();
        ArrayList<Integer> tiempo7 = new ArrayList();
        ArrayList<Integer> peso7 = new ArrayList();
        ArrayList<Integer> tiempo8 = new ArrayList();
        ArrayList<Integer> peso8 = new ArrayList();
        ArrayList<Integer> tiempo9 = new ArrayList();
        ArrayList<Integer> peso9 = new ArrayList();
        ArrayList<Integer> tiempo10 = new ArrayList();
        ArrayList<Integer> peso10 = new ArrayList();
        
        String Codigo_Semilla = "";
        Codigo_Semilla = txt_cod_sem;
        int next = Integer.parseInt(txt_ex_regitro);
        Statement estado;
         Grafica gr=new Grafica(null, true);
        for (int i = 1; i <= next; i++) {

            try {
                String SQL = "SELECT * FROM `medicion` WHERE `cod_num_exp`= '" + Codigo_Semilla + "." + i + "'";
                estado = cn.createStatement();
                ResultSet resultado = estado.executeQuery(SQL);
                //JOptionPane.showMessageDialog(null, SQL);
                while (resultado.next()) {
                   
                    int cod = resultado.getInt(1);
                    //  JOptionPane.showMessageDialog(null, cod);
                    int v_tiempo = resultado.getInt(2);
                    int v_peso = resultado.getInt(5);

                    String cod_num_exp = resultado.getString(8);

                    if (i == 1) {
                        tiempo1.add(v_tiempo);
                        peso1.add(v_peso);
                    }
                    if (i == 2) {
                        tiempo2.add(v_tiempo);
                        peso2.add(v_peso);
                    }
                    if (i == 3) {
                        tiempo3.add(v_tiempo);
                        peso3.add(v_peso);
                    }
                    if (i == 4) {
                        tiempo4.add(v_tiempo);
                        peso4.add(v_peso);
                    }
                    if (i == 5) {
                        tiempo5.add(v_tiempo);
                        peso5.add(v_peso);
                    }
                    if (i == 6) {
                        tiempo6.add(v_tiempo);
                        peso6.add(v_peso);
                    }
                    if (i == 7) {
                        tiempo7.add(v_tiempo);
                        peso7.add(v_peso);
                    }
                     if(i==8){
                        tiempo8.add(v_tiempo);
                    peso8.add(v_peso);
                    }
                    if(i==9){
                        tiempo9.add(v_tiempo);
                    peso9.add(v_peso);
                    }
                      if(i==10){
                        tiempo10.add(v_tiempo);
                    peso10.add(v_peso);
                    }
                     
                }

            } catch (SQLException ex) {
             

            }

        }

        
             Controlador.Grafica gra1=new Controlador.Grafica("PERDIDA DE MASA(%)", "PERDIDA DE MASA(%) vs TIEMPO",next );
              gr.txt_nom_semilla.setText(txt_nombre_semilla.getText().toString());
              gr.txt_num_expe.setText(txt_ex_regitro);
        if (next ==1) {
          //  JOptionPane.showMessageDialog(null," entro");
           
            
        gra1.addgrafica(tiempo1, peso1);
       
         gra1.IniciarGraficaGeneral(gr.p_grafica);
        
        }// fin if
        if (next ==2) {
          //  JOptionPane.showMessageDialog(null," entro");
            
           gra1.addgrafica2(tiempo1, peso1,tiempo2, peso2);
       
           gra1.IniciarGraficaGeneral(gr.p_grafica);
        
        }// fin if
        if (next ==3) {
          //  JOptionPane.showMessageDialog(null," entro");
           
            
            
           gra1.addgrafica3(tiempo1, peso1, tiempo2, peso2, tiempo3, peso3);
      
         gra1.IniciarGraficaGeneral(gr.p_grafica);
        
        }// fin if
        
        if (next ==4) {
          //  JOptionPane.showMessageDialog(null," entro");
           
          
            gra1.addgrafica4(tiempo1, peso1, tiempo2, peso2, tiempo3, peso3, tiempo4, peso4);
      
         gra1.IniciarGraficaGeneral(gr.p_grafica);
        
        }// fin if
        
        if (next ==5) {
          //  JOptionPane.showMessageDialog(null," entro");
           
            
          
            gra1.addgrafica5(tiempo1, peso1, tiempo2, peso2, tiempo3, peso3, tiempo4, peso4, tiempo5, peso5);
      
         gra1.IniciarGraficaGeneral(gr.p_grafica);
        
        }//
        
        
        
        
        
         gr.setVisible(true);
        doClose(RET_OK);
   }// fin if
   else{
     alerta("Alerta", "Aun faltan Experimentos que Registrar", "/Img_alertas/Error_100px.png");   
 txt_mensaje_exp.setText("¡ Aun Faltan experiementos que registrar para esta semilla!");
   }
    }//GEN-LAST:event_btn_graficar2ActionPerformed

    private void btn_graficar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_graficar3ActionPerformed
        // TODO add your handling code here:
         int registros=Integer.parseInt(txt_exp_registrados);
int num_exp=Integer.parseInt(txt_ex_regitro);
   if(registros==num_exp){
        ArrayList<Integer> tiempo1 = new ArrayList();
        ArrayList<Integer> peso1 = new ArrayList();
        ArrayList<Integer> tiempo2 = new ArrayList();
        ArrayList<Integer> peso2 = new ArrayList();
        ArrayList<Integer> tiempo3 = new ArrayList();
        ArrayList<Integer> peso3 = new ArrayList();
        ArrayList<Integer> tiempo4 = new ArrayList();
        ArrayList<Integer> peso4 = new ArrayList();
        ArrayList<Integer> tiempo5 = new ArrayList();
        ArrayList<Integer> peso5 = new ArrayList();
        ArrayList<Integer> tiempo6 = new ArrayList();
        ArrayList<Integer> peso6 = new ArrayList();
        ArrayList<Integer> tiempo7 = new ArrayList();
        ArrayList<Integer> peso7 = new ArrayList();
        ArrayList<Integer> tiempo8 = new ArrayList();
        ArrayList<Integer> peso8 = new ArrayList();
        ArrayList<Integer> tiempo9 = new ArrayList();
        ArrayList<Integer> peso9 = new ArrayList();
        ArrayList<Integer> tiempo10 = new ArrayList();
        ArrayList<Integer> peso10 = new ArrayList();
        
        String Codigo_Semilla = "";
        Codigo_Semilla = txt_cod_sem;
        int next = Integer.parseInt(txt_ex_regitro);
        Statement estado;
         Grafica gr=new Grafica(null, true);
        for (int i = 1; i <= next; i++) {

            try {
                String SQL = "SELECT * FROM `medicion` WHERE `cod_num_exp`= '" + Codigo_Semilla + "." + i + "'";
                estado = cn.createStatement();
                ResultSet resultado = estado.executeQuery(SQL);
                //JOptionPane.showMessageDialog(null, SQL);
                while (resultado.next()) {
                   
                    int cod = resultado.getInt(1);
                    //  JOptionPane.showMessageDialog(null, cod);
                    int v_tiempo = resultado.getInt(2);
                    int v_peso = resultado.getInt(6);

                    String cod_num_exp = resultado.getString(8);

                    if (i == 1) {
                        tiempo1.add(v_tiempo);
                        peso1.add(v_peso);
                    }
                    if (i == 2) {
                        tiempo2.add(v_tiempo);
                        peso2.add(v_peso);
                    }
                    if (i == 3) {
                        tiempo3.add(v_tiempo);
                        peso3.add(v_peso);
                    }
                    if (i == 4) {
                        tiempo4.add(v_tiempo);
                        peso4.add(v_peso);
                    }
                    if (i == 5) {
                        tiempo5.add(v_tiempo);
                        peso5.add(v_peso);
                    }
                    if (i == 6) {
                        tiempo6.add(v_tiempo);
                        peso6.add(v_peso);
                    }
                    if (i == 7) {
                        tiempo7.add(v_tiempo);
                        peso7.add(v_peso);
                    }
                     if(i==8){
                        tiempo8.add(v_tiempo);
                    peso8.add(v_peso);
                    }
                    if(i==9){
                        tiempo9.add(v_tiempo);
                    peso9.add(v_peso);
                    }
                      if(i==10){
                        tiempo10.add(v_tiempo);
                    peso10.add(v_peso);
                    }
                     
                }

            } catch (SQLException ex) {
             

            }

        }

        
             Controlador.Grafica gra1=new Controlador.Grafica("HUMEDAD", "HUMEDAD vs TIEMPO",next );
              gr.txt_nom_semilla.setText(txt_nombre_semilla.getText().toString());
              gr.txt_num_expe.setText(txt_ex_regitro);
        if (next ==1) {
          //  JOptionPane.showMessageDialog(null," entro");
           
            
        gra1.addgrafica(tiempo1, peso1);
       
         gra1.IniciarGraficaGeneral(gr.p_grafica);
        
        }// fin if
        if (next ==2) {
          //  JOptionPane.showMessageDialog(null," entro");
            
           gra1.addgrafica2(tiempo1, peso1,tiempo2, peso2);
       
           gra1.IniciarGraficaGeneral(gr.p_grafica);
        
        }// fin if
        if (next ==3) {
          //  JOptionPane.showMessageDialog(null," entro");
           
            
            
           gra1.addgrafica3(tiempo1, peso1, tiempo2, peso2, tiempo3, peso3);
      
         gra1.IniciarGraficaGeneral(gr.p_grafica);
        
        }// fin if
        
        if (next ==4) {
          //  JOptionPane.showMessageDialog(null," entro");
           
          
            gra1.addgrafica4(tiempo1, peso1, tiempo2, peso2, tiempo3, peso3, tiempo4, peso4);
      
         gra1.IniciarGraficaGeneral(gr.p_grafica);
        
        }// fin if
        
        if (next ==5) {
          //  JOptionPane.showMessageDialog(null," entro");
           
            
          
            gra1.addgrafica5(tiempo1, peso1, tiempo2, peso2, tiempo3, peso3, tiempo4, peso4, tiempo5, peso5);
      
         gra1.IniciarGraficaGeneral(gr.p_grafica);
        
        }//
        
        
        
        
        
         gr.setVisible(true);
        doClose(RET_OK);
   }// fin if
   else{
     alerta("Alerta", "Aun faltan Experimentos que Registrar", "/Img_alertas/Error_100px.png");   
 txt_mensaje_exp.setText("¡ Aun Faltan experiementos que registrar para esta semilla!");
   }
    }//GEN-LAST:event_btn_graficar3ActionPerformed

    private void btn_graficar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_graficar4ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
         int registros=Integer.parseInt(txt_exp_registrados);
int num_exp=Integer.parseInt(txt_ex_regitro);
   if(registros==num_exp){
        ArrayList<Integer> tiempo1 = new ArrayList();
        ArrayList<Integer> peso1 = new ArrayList();
        ArrayList<Integer> tiempo2 = new ArrayList();
        ArrayList<Integer> peso2 = new ArrayList();
        ArrayList<Integer> tiempo3 = new ArrayList();
        ArrayList<Integer> peso3 = new ArrayList();
        ArrayList<Integer> tiempo4 = new ArrayList();
        ArrayList<Integer> peso4 = new ArrayList();
        ArrayList<Integer> tiempo5 = new ArrayList();
        ArrayList<Integer> peso5 = new ArrayList();
        ArrayList<Integer> tiempo6 = new ArrayList();
        ArrayList<Integer> peso6 = new ArrayList();
        ArrayList<Integer> tiempo7 = new ArrayList();
        ArrayList<Integer> peso7 = new ArrayList();
        ArrayList<Integer> tiempo8 = new ArrayList();
        ArrayList<Integer> peso8 = new ArrayList();
        ArrayList<Integer> tiempo9 = new ArrayList();
        ArrayList<Integer> peso9 = new ArrayList();
        ArrayList<Integer> tiempo10 = new ArrayList();
        ArrayList<Integer> peso10 = new ArrayList();
        
        String Codigo_Semilla = "";
        Codigo_Semilla = txt_cod_sem;
        int next = Integer.parseInt(txt_ex_regitro);
        Statement estado;
         Grafica gr=new Grafica(null, true);
        for (int i = 1; i <= next; i++) {

            try {
                String SQL = "SELECT * FROM `medicion` WHERE `cod_num_exp`= '" + Codigo_Semilla + "." + i + "'";
                estado = cn.createStatement();
                ResultSet resultado = estado.executeQuery(SQL);
                //JOptionPane.showMessageDialog(null, SQL);
                while (resultado.next()) {
                   
                    int cod = resultado.getInt(1);
                    //  JOptionPane.showMessageDialog(null, cod);
                    int v_tiempo = resultado.getInt(2);
                    int v_peso = resultado.getInt(7);

                    String cod_num_exp = resultado.getString(8);

                    if (i == 1) {
                        tiempo1.add(v_tiempo);
                        peso1.add(v_peso);
                    }
                    if (i == 2) {
                        tiempo2.add(v_tiempo);
                        peso2.add(v_peso);
                    }
                    if (i == 3) {
                        tiempo3.add(v_tiempo);
                        peso3.add(v_peso);
                    }
                    if (i == 4) {
                        tiempo4.add(v_tiempo);
                        peso4.add(v_peso);
                    }
                    if (i == 5) {
                        tiempo5.add(v_tiempo);
                        peso5.add(v_peso);
                    }
                    if (i == 6) {
                        tiempo6.add(v_tiempo);
                        peso6.add(v_peso);
                    }
                    if (i == 7) {
                        tiempo7.add(v_tiempo);
                        peso7.add(v_peso);
                    }
                     if(i==8){
                        tiempo8.add(v_tiempo);
                    peso8.add(v_peso);
                    }
                    if(i==9){
                        tiempo9.add(v_tiempo);
                    peso9.add(v_peso);
                    }
                      if(i==10){
                        tiempo10.add(v_tiempo);
                    peso10.add(v_peso);
                    }
                     
                }

            } catch (SQLException ex) {
             

            }

        }

        
             Controlador.Grafica gra1=new Controlador.Grafica("VELOCIDAD PERDIDA DE MASA", "VELOCIDAD PERDIDAD DE MASA vs TIEMPO",next );
              gr.txt_nom_semilla.setText(txt_nombre_semilla.getText().toString());
              gr.txt_num_expe.setText(txt_ex_regitro);
        if (next ==1) {
          //  JOptionPane.showMessageDialog(null," entro");
           
            
        gra1.addgrafica(tiempo1, peso1);
       
         gra1.IniciarGraficaGeneral(gr.p_grafica);
        
        }// fin if
        if (next ==2) {
          //  JOptionPane.showMessageDialog(null," entro");
            
           gra1.addgrafica2(tiempo1, peso1,tiempo2, peso2);
       
           gra1.IniciarGraficaGeneral(gr.p_grafica);
        
        }// fin if
        if (next ==3) {
          //  JOptionPane.showMessageDialog(null," entro");
           
            
            
           gra1.addgrafica3(tiempo1, peso1, tiempo2, peso2, tiempo3, peso3);
      
         gra1.IniciarGraficaGeneral(gr.p_grafica);
        
        }// fin if
        
        if (next ==4) {
          //  JOptionPane.showMessageDialog(null," entro");
           
          
            gra1.addgrafica4(tiempo1, peso1, tiempo2, peso2, tiempo3, peso3, tiempo4, peso4);
      
         gra1.IniciarGraficaGeneral(gr.p_grafica);
        
        }// fin if
        
        if (next ==5) {
          //  JOptionPane.showMessageDialog(null," entro");
           
            
          
            gra1.addgrafica5(tiempo1, peso1, tiempo2, peso2, tiempo3, peso3, tiempo4, peso4, tiempo5, peso5);
      
         gra1.IniciarGraficaGeneral(gr.p_grafica);
        
        }//
        
        
        
        
        
         gr.setVisible(true);
        doClose(RET_OK);
   }// fin if
   else{
     alerta("Alerta", "Aun faltan Experimentos que Registrar", "/Img_alertas/Error_100px.png");   
 txt_mensaje_exp.setText("¡ Aun Faltan experiementos que registrar para esta semilla!");
   }
    }//GEN-LAST:event_btn_graficar4ActionPerformed
    public void consutarTabla_Estudiantes(rojerusan.RSTableMetro Tabla_p) {

        String consultaBD = "SELECT * FROM `experimento_secado` ";
        javax.swing.JTable Tabla = Tabla_p;
        // Enviamos los parametros para la consulta de la tabla
        //  conexion    consulta de la base de datos y el nombre de la tabla
        String cabesera[] = {"Código", "Nombre de la Semilla", "Numero Experimentos", "Fecha"};
        cone1.GetTabla_Sincabeseras_sql_bd(cn, consultaBD, Tabla, cabesera);

    }

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    public int confirmar(int res) {

        if (res == 1) {
            respuesta = 1;
        }
        if (res == 0) {
            respuesta = 0;
        }
        if (res == 3) {
            respuesta = 3;
        }

        return respuesta;

    }
public void alerta(String titulo, String texto, String dir_img) {

        Alertas wa = new Alertas(null, true);
        wa.txt_titu.setText(titulo);
        wa.txt_txt.setText(texto);

        wa.txt_img.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir_img)));

        wa.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_TipoGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_TipoGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_TipoGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_TipoGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Menu_TipoGrafica dialog = new Menu_TipoGrafica(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonMetro btn_graficar;
    public rojerusan.RSButtonMetro btn_graficar1;
    public rojerusan.RSButtonMetro btn_graficar2;
    public rojerusan.RSButtonMetro btn_graficar3;
    public rojerusan.RSButtonMetro btn_graficar4;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel txt_ex_regitro1;
    public javax.swing.JLabel txt_mensaje_exp;
    public javax.swing.JLabel txt_nombre_semilla;
    public javax.swing.JLabel txt_titu;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
