/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas_paneles;

import Controlador.Main;
import Controlador.cambia_panel;
import Modelo.Datos;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import tabla.MyScrollbarUI;

/**
 *
 * @author Danilo
 */
public class Menu_requerimiento extends javax.swing.JDialog {
 

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;
     public  int  respuesta=3;
     
       Datos d= new Datos();
      String direccionBD = d.getDireccionBD();
      String usuarioBD = d.getUsuarioBD();
      String contraBD = d.getContraBD();
    // Instanciamos la clase conectar 
    Modelo.conectar cone1 = new Modelo.conectar();
    // realizamos la conexion
    public Connection cn = cone1.conexion(direccionBD, usuarioBD, contraBD);
     
     
     
     

    /**
     * Creates new form Alertas
     */
    public Menu_requerimiento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(this);
        btn_reg_exp.setEnabled(false);
        
        
        
        
    //   this. setIconImage(new ImageIcon(getClass().getResource("/Img_menu/SEPRYTSAV_45x45PX.png")).getImage());
//jScrollPane1.getVerticalScrollBar().setUI(new MyScrollbarUI());
//        jScrollPane1.getHorizontalScrollBar().setUI(new MyScrollbarUI());
        
        
txt_cod_sem.setText("");
txt_nombre_semilla.setText("");
txt_exp_registrados.setText("");
  txt_ex_regitro.setText("");
        
txt_mensaje_exp.setText("");
        
        
        
        
        
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        btn_reg_exp = new rojerusan.RSButtonMetro();
        txt_cod_sem = new rojerusan.RSMetroTextPlaceHolder();
        txt_titu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_ex_regitro = new javax.swing.JLabel();
        txt_exp_registrados = new javax.swing.JLabel();
        txt_mensaje = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_cod_est = new rojerusan.RSButtonMetro();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre_semilla = new javax.swing.JLabel();
        txt_mensaje_exp = new javax.swing.JLabel();
        txt_ex_regitro1 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(21, 96, 136));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        btn_reg_exp.setBackground(new java.awt.Color(21, 96, 136));
        btn_reg_exp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Regis_exp_52px.png"))); // NOI18N
        btn_reg_exp.setText("Registra Experimento");
        btn_reg_exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg_expActionPerformed(evt);
            }
        });

        txt_cod_sem.setForeground(new java.awt.Color(27, 108, 155));
        txt_cod_sem.setBorderColor(new java.awt.Color(21, 96, 136));
        txt_cod_sem.setBotonColor(new java.awt.Color(21, 96, 136));
        txt_cod_sem.setCaretColor(new java.awt.Color(21, 96, 136));
        txt_cod_sem.setDisabledTextColor(new java.awt.Color(27, 108, 155));
        txt_cod_sem.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_cod_sem.setPhColor(new java.awt.Color(27, 108, 155));
        txt_cod_sem.setPlaceholder("Código Semilla:");
        txt_cod_sem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cod_semActionPerformed(evt);
            }
        });

        txt_titu.setBackground(new java.awt.Color(21, 96, 136));
        txt_titu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_titu.setForeground(new java.awt.Color(21, 96, 136));
        txt_titu.setText("Opciones de experimento");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 96, 136));
        jLabel1.setText("Experimentos registrados:");

        txt_ex_regitro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_ex_regitro.setForeground(new java.awt.Color(255, 51, 51));
        txt_ex_regitro.setText("0");

        txt_exp_registrados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_exp_registrados.setForeground(new java.awt.Color(255, 51, 51));
        txt_exp_registrados.setText("0");

        txt_mensaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_mensaje.setForeground(new java.awt.Color(21, 96, 136));
        txt_mensaje.setText("Mensaje:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(21, 96, 136));
        jLabel5.setText("de");

        btn_cod_est.setBackground(new java.awt.Color(21, 96, 136));
        btn_cod_est.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/seleccionar_52px.png"))); // NOI18N
        btn_cod_est.setText("Seleccionar Semilla");
        btn_cod_est.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cod_estActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(21, 96, 136));
        jLabel2.setText("Nombre de la Semilla:");

        txt_nombre_semilla.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_nombre_semilla.setForeground(new java.awt.Color(21, 96, 136));

        txt_mensaje_exp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_mensaje_exp.setForeground(new java.awt.Color(255, 51, 51));

        txt_ex_regitro1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_ex_regitro1.setForeground(new java.awt.Color(255, 51, 51));
        txt_ex_regitro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/opc_experimento52px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_nombre_semilla, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_exp_registrados, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_ex_regitro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(txt_cod_sem, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_cod_est, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(txt_mensaje)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_mensaje_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(txt_titu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(txt_ex_regitro1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_reg_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txt_ex_regitro1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_titu)
                .addGap(26, 26, 26)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cod_sem, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cod_est, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_nombre_semilla, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_exp_registrados)
                    .addComponent(jLabel5)
                    .addComponent(txt_ex_regitro))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_mensaje)
                    .addComponent(txt_mensaje_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_reg_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void btn_reg_expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg_expActionPerformed
        
        int NumeroExp= Integer.parseInt(txt_exp_registrados.getText().toString());
        int suma=NumeroExp+1;
        
        Esperimento ex = new Esperimento();
        ex.txt_nExperimento.setText(String.valueOf(suma));
        ex.codigo_semilla=txt_cod_sem.getText().toString();
        ex.Num_exp=txt_ex_regitro.getText().toString();
        ex.Nombre_semilla=txt_nombre_semilla.getText().toString();
       Main.m.pintar(3);
        new cambia_panel(Main.m.panel_master, ex);
        doClose(RET_OK);
        
        
        
        txt_cod_sem.setText("");
txt_nombre_semilla.setText("");
txt_exp_registrados.setText("");
  txt_ex_regitro.setText("");
        
txt_mensaje_exp.setText("");
        

    }//GEN-LAST:event_btn_reg_expActionPerformed

    private void txt_cod_semActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cod_semActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cod_semActionPerformed

    private void btn_cod_estActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cod_estActionPerformed
        // TODO add your handling code here:
        btn_reg_exp.setEnabled(false);
        txt_mensaje_exp.setText("");
        Busqueda_semillas bs=new Busqueda_semillas(null, true);
 String cabesera[] = {"Código", "Nombre de la Semilla", "Numero Experimentos", "Fecha"};
       
        consutarTabla_Estudiantes(bs.Tabla_Seleccion);
        bs.Entidad="experimento_secado";
        bs.cabesera_general= cabesera;
         bs.setVisible(true);
         
    }//GEN-LAST:event_btn_cod_estActionPerformed
     public void consutarTabla_Estudiantes(rojerusan.RSTableMetro Tabla_p) {

        String consultaBD = "SELECT * FROM `experimento_secado` ";
        javax.swing.JTable Tabla = Tabla_p;
        // Enviamos los parametros para la consulta de la tabla
        //  conexion    consulta de la base de datos y el nombre de la tabla
        String cabesera[] = {"Código", "Nombre de la Semilla", "Numero Experimentos", "Fecha"};
        cone1.GetTabla_Sincabeseras_sql_bd(cn, consultaBD, Tabla, cabesera);

    }
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    public int confirmar(int res){
     
        if(res==1){
            respuesta=1;
        }
        if(res==0){
            respuesta=0;
        }
        if(res==3){
            respuesta=3;
        }
        
        return respuesta;
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_requerimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_requerimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_requerimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_requerimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Menu_requerimiento dialog = new Menu_requerimiento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonMetro btn_cod_est;
    public rojerusan.RSButtonMetro btn_reg_exp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    public rojerusan.RSMetroTextPlaceHolder txt_cod_sem;
    public javax.swing.JLabel txt_ex_regitro;
    public javax.swing.JLabel txt_ex_regitro1;
    public javax.swing.JLabel txt_exp_registrados;
    private javax.swing.JLabel txt_mensaje;
    public javax.swing.JLabel txt_mensaje_exp;
    public javax.swing.JLabel txt_nombre_semilla;
    public javax.swing.JLabel txt_titu;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
